In [2]:
import numpy as np

#1D with Numpy

List를 생성하여 np.array로 1차원 array로 변환

In [13]:
t = np.array([0,1,2,3,4,5,6], dtype = float)
print(t)

[0. 1. 2. 3. 4. 5. 6.]


이제 1차원 텐서의 벡터 차원 및 크기 출력

In [14]:
print("Rank of t: ", t.ndim) 
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


- ndim은 차원의 크기로, 3이면 3D Tensor, 2면 2D 텐서
- shape은 데이터 크기로, (7,)은 (1,7)을 의미. 즉 1 x 7의 크기를 가지는 벡터

# 2D with numpy

In [15]:
t = np.array([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]], dtype = float)
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [16]:
print("Rank of t: ", t.ndim) 
print("Shape of t: ", t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# 파이토치 텐서 선언하기(Pytorch Tensor Allocation)

In [18]:
import torch

## 1D with Pytorch

In [22]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [23]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [24]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D with PyTorch

In [28]:
t = torch.FloatTensor([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [30]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


2차원 텐서이며, (4,3)의 크기를 가짐

## 브로드캐스팅(BroadCasting)

- 행렬의 덧셈, 곱셈을 수행 시 두 행렬의 크기가 같아야 하며, 곱셈 시 두 차원이 일치해야 함
- 단, 딥러닝을 하게 되면, 불가피하게 크기가 다른 행렬 또는 텐서에 대해 사칙연산을 수행할 필요가 생김
- 이를 위해 자동으로 크기를 맞춰 연산을 수행해주는 **브로드캐스팅**이라는 기능 제공

In [35]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1,m2)
print(m1+m2)

tensor([[3., 3.]]) tensor([[2., 2.]])
tensor([[5., 5.]])


두 텐서의 크기는 둘 다 (1,2)로 덧셈 연산은 문제가 없음

In [37]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1,m2)
print(m1+m2)

tensor([[1., 2.]]) tensor([[3.]])
tensor([[4., 5.]])


m2의 크기가 (1,)인데 파이토치는 (1,2)로 변경하여 연산을 수행

---

이번엔 2차원 텐서를 대상으로 브로드캐스팅 적용

In [38]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


- (1,2)인 m1과 (2,1)인 m2를 연산하기 위해 둘 다 (2,2) 크기의 텐서로 자동 변환하여 연산 수행
- 이러한 기능은 매우 유용하지만 매우 주의해야 함
- **브로드캐스팅은 자동으로 수행되므로 나중에 원하는 결과가 나오지 않는 경우 어디서 문제가 발생했는지 찾기가 매우 힘듦**

## 자주 사용되는 기능들

### 행렬의 곱셈과 곱셈의 차이(Matrix Multiplication vs Multiplication)
---
행렬의 곱셈은 두 가지로,
- 행렬 곱셈 : numpy와 같은 matmul()
- 원소 곱셈 : 원소별 곱셈인 (*) or mul()

#### Matmul() - 행렬 곱셈

In [45]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


#### Mul() - 원소 곱셈

In [48]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.mul(m2)) # 2 x 2
print(m1*m2) # 2 x 2

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 평균(Mean)
---
numpy의 mean과 매우 유사

In [50]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [51]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


여기서 열단위 혹은 행단위로 평균을 구할 수도 있음

In [56]:
print("행 단위(dim = 0)",t.mean(dim = 0)) #행 단위
print("열 단위(dim = 1)",t.mean(dim = 1)) #열 단위
print("마지막 차원 단위(dim = -1)",t.mean(dim = -1)) #마지막 차원 방향

행 단위(dim = 0) tensor([2., 3.])
열 단위(dim = 1) tensor([1.5000, 3.5000])
마지막 차원 단위(dim = -1) tensor([1.5000, 3.5000])


### 덧셈(sum)
---
평균과 동일하게 동작하며, 평균이 아닌 값을 덧셈

In [57]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [59]:
print(t.sum()) # 원소 전체
print(t.sum(dim=0)) # 행 단위
print(t.sum(dim=1)) # 열 단위
print(t.sum(dim=-1)) # 마지막 차원 단위

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### 최대 or 최소 값

In [60]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [62]:
print(t.max()) #전체 중 최대 값
print("*"*30)
print(t.max(dim=0)) #행 기준 최대 값
print("*"*30)
print(t.max(dim=1)) #열 기준 최대 값

tensor(4.)
******************************
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
******************************
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


- 특정 dim을 지정한 경우, 찾는 영역에서의 최대 값과 그 index값이 출력됨
- armax값을 받아오고자 할 경우 아래와 같음

In [68]:
print(t.max(dim=0))
print("*"*30)
print(t.max(dim=0)[1])
print("*"*30)
print(t.max(dim=0)[1][0])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
******************************
tensor([1, 1])
******************************
tensor(1)
